### ISSUE TITLE
Another crash

### ISSUE THREAD

**Issue by Cocklet** [AzureDoom/AzureDoom-Doom-Mod#22] opened 2020-11-30 08:30 UTC
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 11/30/20 3:03 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.ai.controller.LookController.func_75651_a(SourceFile:31) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.func_75246_d(MeleeAttackGoal.java:98) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:88) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:syp:MobEntity,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:syp:MobEntity,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:43) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:syp:MobEntity,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:399) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:283) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:229) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.ai.controller.LookController.func_75651_a(SourceFile:31) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.func_75246_d(MeleeAttackGoal.java:98) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:88) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:syp:MobEntity,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:syp:MobEntity,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:43) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:syp:MobEntity,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Entity being ticked --
Details:
	Entity Type: doomweapon:shotgunguy (mod.azure.doom.entity.ShotgunguyEntity)
	Entity ID: 31258
	Entity Name: Arcane Shotgun Guy
	Entity's Exact location: 1486.13, 62.00, 64.09
	Entity's Block location: World: (1486,62,64), Chunk: (at 14,3,0 in 92,4; contains blocks 1472,0,64 to 1487,255,79), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:399) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}

-- Affected level --
Details:
	All players: 2 total; [ServerPlayerEntity['SwampyRooster'/3575, l='ServerLevel[OOF]', x=1432.34, y=61.00, z=73.41], ServerPlayerEntity['Penguins7187'/299, l='ServerLevel[OOF]', x=1432.40, y=63.25, z=70.17]]
	Chunk stats: ServerChunkCache: 1618
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (-64,76,243), Chunk: (at 0,4,3 in -4,15; contains blocks -64,0,240 to -49,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 555586 game time, 555586 day time
	Level name: OOF
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 39320 (now: false), thunder time: 133640 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:283) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:229) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3386241256 bytes (3229 MB) / 6319767552 bytes (6027 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 12
	JVM Flags: 4 total; -Xms0G -Xmx6G -XX:+UseG1GC -Xmx6144M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.42.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.42
	FML Language Providers: 
		javafml@34.1
		minecraft@1
		kotlinforforge@1.6.2
	Mod List: 
		DungeonsMod-1.16.3-1.1.1.jar                      |Dungeons Mod                  |dungeonsmod                   |1.16.3-1.1.1        |DONE      |NOSIGNATURE
		randomloot-2.1.7.jar                              |Random Loot Mod               |randomloot                    |2.1.7               |DONE      |NOSIGNATURE
		GokiStats-1.16.3-1.2.12.jar                       |Goki Stats                    |gokistats                     |1.2.12              |DONE      |NOSIGNATURE
		Wyrmroost-1.16.3-1.2.7.jar                        |Wyrmroost                     |wyrmroost                     |1.16.3-1.2.7        |DONE      |NOSIGNATURE
		jei-1.16.3-7.6.0.51.jar                           |Just Enough Items             |jei                           |7.6.0.50            |DONE      |NOSIGNATURE
		AttributeFix-1.16.3-8.0.1.jar                     |AttributeFix                  |attributefix                  |8.0.1               |DONE      |NOSIGNATURE
		DoggyTalents-1.16.3-2.0.1.0.jar                   |Doggy Talents 2               |doggytalents                  |2.0.1.0             |DONE      |NOSIGNATURE
		goblintraders-1.2.2-1.16.3.jar                    |Goblin Traders                |goblintraders                 |1.2.2               |DONE      |NOSIGNATURE
		BetterCaves-1.16.2-1.0.4.jar                      |YUNG's Better Caves           |bettercaves                   |1.16.2-1.0.4        |DONE      |NOSIGNATURE
		ForgeEndertech-1.16.3-7.0.6.0-build.0024.jar      |Forge Endertech               |forgeendertech                |7.0.6.0             |DONE      |NOSIGNATURE
		Clumps-6.0.0.12.jar                               |Clumps                        |clumps                        |6.0.0.12            |DONE      |NOSIGNATURE
		Placebo-1.16.3-4.3.3.jar                          |Placebo                       |placebo                       |4.3.3               |DONE      |NOSIGNATURE
		citadel-1.4.1.jar                                 |Citadel                       |citadel                       |1.4.1               |DONE      |NOSIGNATURE
		decorative_blocks-1.16.2-1.1.jar                  |Decorative Blocks             |decorative_blocks             |1.5                 |DONE      |NOSIGNATURE
		VanillaTweaks-1.16.4-1.5.34.jar                   |VanillaTweaks                 |vanillatweaks                 |1.16.4-1.5.34       |DONE      |NOSIGNATURE
		champions-forge-1.16.3-2.0.0.1.jar                |Champions                     |champions                     |1.16.3-2.0.0.1      |DONE      |NOSIGNATURE
		DungeonCrawl-1.16.3-2.2.1.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.2.1               |DONE      |NOSIGNATURE
		MutantBeasts-1.16.3-1.1.2.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.3-1.1.2        |DONE      |d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		Bookshelf-1.16.3-8.7.20.jar                       |Bookshelf                     |bookshelf                     |8.7.20              |DONE      |NOSIGNATURE
		MoreCraft_1.16.3-4.2b3.jar                        |MoreCraft                     |morecraft                     |4.2b3               |DONE      |NOSIGNATURE
		u_team_core-1.16.3-3.1.12.185.jar                 |U Team Core                   |uteamcore                     |3.1.12.185          |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		mapperbase-1.16.3-2.2.0.0.jar                     |Mapper Base                   |mapperbase                    |1.16.3-2.2.0.0      |DONE      |NOSIGNATURE
		iceandfire-2.1.2-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.2-1.16.4        |DONE      |NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |NOSIGNATURE
		WAWLA-1.16.3-6.0.1.jar                            |WAWLA                         |wawla                         |6.0.1               |DONE      |NOSIGNATURE
		VTweaks-1.16.3-3.1.9.jar                          |V-Tweaks                      |vtweaks                       |3.1.9               |DONE      |NOSIGNATURE
		JustEnoughResources-1.16.3-0.12.0.100.jar         |Just Enough Resources         |jeresources                   |0.12.0.100          |DONE      |NOSIGNATURE
		forge-1.16.3-34.1.42-universal.jar                |Forge                         |forge                         |34.1.42             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		shetiphiancore-1.16-3.8.4.jar                     |ShetiPhian-Core               |shetiphiancore                |3.8.4               |DONE      |NOSIGNATURE
		structure-gel-api-1.16.3-1.6.0.jar                |Structure Gel API             |structure_gel                 |1.6.0               |DONE      |NOSIGNATURE
		forge-1.16.3-34.1.42-server.jar                   |Minecraft                     |minecraft                     |1.16.3              |DONE      |NOSIGNATURE
		cofh_core-1.16.3-1.0.4.jar                        |CoFH Core                     |cofh_core                     |1.0.4               |DONE      |NOSIGNATURE
		ensorcellation-1.16.3-1.0.3.jar                   |Ensorcellation                |ensorcellation                |1.0.3               |DONE      |NOSIGNATURE
		useful_backpacks-1.16.3-1.11.6.84.jar             |Useful Backpacks              |usefulbackpacks               |1.11.6.84           |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		repurposed_structures-1.16.3-2.2.11.jar           |Repurposed Structures         |repurposed_structures         |1.16.3-2.2.11       |DONE      |NOSIGNATURE
		EnchantmentDescriptions-1.16.3-5.0.1.jar          |EnchantmentDescriptions       |enchdesc                      |5.0.1               |DONE      |NOSIGNATURE
		swingthroughgrass-1.16.3-1.5.2.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.3-1.5.2        |DONE      |NOSIGNATURE
		pandoras_creatures-1.16.3-2.0.1.jar               |Pandoras Creatures            |pandoras_creatures            |1.16.3-2.0.1        |DONE      |NOSIGNATURE
		embellishcraft-1.16.3-3.2.0.0.jar                 |EmbellishCraft                |embellishcraft                |1.16.3-3.2.0.0      |DONE      |NOSIGNATURE
		MouseTweaks-2.13-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.13                |DONE      |NOSIGNATURE
		greekfantasy-16.3.2.jar                           |Greek Fantasy                 |greekfantasy                  |16.3.2              |DONE      |NOSIGNATURE
		ToolStats-1.16.3-4.0.1.jar                        |ToolStats                     |toolstats                     |4.0.1               |DONE      |NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |DONE      |NOSIGNATURE
		SaveYourPets-1.16.2-1.0.0.4.jar                   |Save Your Pets                |syp                           |1.0.0.4             |DONE      |NOSIGNATURE
		dungeons-plus-1.16.3-1.0.3.jar                    |Dungeons Plus                 |dungeons_plus                 |1.0.3               |DONE      |NOSIGNATURE
		extcaves-2.4.jar                                  |Extended Caves                |extcaves                      |2.4                 |DONE      |NOSIGNATURE
		NetherEnhanced-1.16.3-0.3.jar                     |Nether Enhanced               |netherenhanced                |0.1                 |DONE      |NOSIGNATURE
		AzureDooms-Doom-Mod-1.16.4-3.4.5.jar              |Doom Mod                      |doomweapon                    |3.4.5               |DONE      |NOSIGNATURE
		curios-forge-1.16.3-4.0.2.0.jar                   |Curios API                    |curios                        |1.16.3-4.0.2.0      |DONE      |NOSIGNATURE
		Artifacts-1.16.3-2.6.0.jar                        |Artifacts                     |artifacts                     |1.16.3-2.6.0        |DONE      |NOSIGNATURE
		ftb-backups-2.1.1.6.jar                           |FTB Backups                   |ftbbackups                    |2.1.1.6             |DONE      |NOSIGNATURE
		AutoRegLib-1.6-46.jar                             |AutoRegLib                    |autoreglib                    |1.6-46              |DONE      |NOSIGNATURE
		Quark-r2.4-275.jar                                |Quark                         |quark                         |r2.4-275            |DONE      |NOSIGNATURE
		Apotheosis-1.16.3-4.4.1.jar                       |Apotheosis                    |apotheosis                    |4.4.1               |DONE      |NOSIGNATURE
		WorldPreGenerator-1.16.3-1.0.0.jar                |World Pre Generator           |world_pre_generator           |1.0.0               |DONE      |NOSIGNATURE
		Regrowth-1.16.2-1.16.3-1.21.0.14.jar              |Regrowth Mod                  |regrowth                      |1.21.0.14           |DONE      |NOSIGNATURE
		Runelic-1.16.3-5.0.1.jar                          |Runelic                       |runelic                       |5.0.1               |DONE      |NOSIGNATURE
		DarkUtilities-1.16.3-6.0.3.jar                    |Dark Utilities                |darkutils                     |6.0.3               |DONE      |NOSIGNATURE
		worldedit-forge-mc1.16.3-7.2.0-dist.jar           |WorldEdit                     |worldedit                     |7.2.0+a51fa43       |DONE      |NOSIGNATURE
		FastFurnace-1.16.2-4.2.0.jar                      |FastFurnace                   |fastfurnace                   |4.2.0               |DONE      |NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |DONE      |NOSIGNATURE
		The_Undergarden-1.16.3-0.3.8.jar                  |The Undergarden               |undergarden                   |0.3.8               |DONE      |NOSIGNATURE
		byg-1.1.2.jar                                     |Oh The Biomes You'll Go       |byg                           |1.1.1               |DONE      |NOSIGNATURE
		Aquaculture-1.16.3-2.1.5.jar                      |Aquaculture 2                 |aquaculture                   |1.16.3-2.1.5        |DONE      |NOSIGNATURE
		FriendlyFire-1.16.3-5.0.3.jar                     |FriendlyFire                  |friendlyfire                  |5.0.3               |DONE      |NOSIGNATURE
		DeExtinction-1.16.3-1.1.0.jar                     |De-Extinction Mod             |deextinction                  |1.1.0               |DONE      |NOSIGNATURE
		terraqueous-1.16-1.7.5.jar                        |Terraqueous                   |terraqueous                   |1.7.5               |DONE      |NOSIGNATURE
		overloadedarmorbar-5.1.0.jar                      |Overloaded Armor Bar          |overloadedarmorbar            |5.1.0               |DONE      |NOSIGNATURE
		BetterMineshaftsForge-1.16.2-1.0.1.jar            |YUNG's Better Mineshafts      |bettermineshafts              |1.16.2-1.0.1        |DONE      |NOSIGNATURE
		forge-1.16.3-geckolib-3.0.0-beta.8.jar            |GeckoLib                      |geckolib3                     |3.0.0-beta.8        |DONE      |NOSIGNATURE
		Cyclic-1.16.3-0.8.3.jar                           |Cyclic                        |cyclic                        |1.16.3-0.8.3        |DONE      |1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		farlanders-1.16.3-1.3.4.jar                       |The Farlanders                |farlanders                    |1.3.4               |DONE      |NOSIGNATURE
		BetterAdvancements-1.16.3-0.1.0.102.jar           |Better Advancements           |betteradvancements            |0.1.0.102           |DONE      |NOSIGNATURE
	Crash Report UUID: 742b31c0-66d0-4742-83dd-613f189a7f4a
	Player Count: 2 / 5; [ServerPlayerEntity['SwampyRooster'/3575, l='ServerLevel[OOF]', x=1432.34, y=61.00, z=73.41], ServerPlayerEntity['Penguins7187'/299, l='ServerLevel[OOF]', x=1432.40, y=63.25, z=70.17]]
	Data Packs: vanilla, mod:dungeonsmod, mod:randomloot (incompatible), mod:gokistats, mod:wyrmroost (incompatible), mod:jei, mod:attributefix, mod:doggytalents (incompatible), mod:goblintraders, mod:bettercaves (incompatible), mod:forgeendertech, mod:clumps (incompatible), mod:placebo (incompatible), mod:citadel (incompatible), mod:decorative_blocks, mod:vanillatweaks, mod:champions (incompatible), mod:dungeoncrawl, mod:mutantbeasts (incompatible), mod:bookshelf, mod:morecraft, mod:uteamcore, mod:mapperbase (incompatible), mod:iceandfire (incompatible), mod:waila, mod:wawla, mod:vtweaks (incompatible), mod:jeresources, mod:forge, mod:shetiphiancore, mod:structure_gel, mod:cofh_core (incompatible), mod:ensorcellation (incompatible), mod:usefulbackpacks, mod:repurposed_structures, mod:enchdesc, mod:swingthroughgrass (incompatible), mod:pandoras_creatures (incompatible), mod:embellishcraft (incompatible), mod:mousetweaks, mod:greekfantasy, mod:toolstats, mod:valhelsia_structures (incompatible), mod:syp, mod:dungeons_plus, mod:extcaves, mod:netherenhanced, mod:doomweapon (incompatible), mod:curios, mod:artifacts (incompatible), mod:ftbbackups (incompatible), mod:autoreglib (incompatible), mod:quark (incompatible), mod:apotheosis (incompatible), mod:world_pre_generator, mod:regrowth, mod:runelic, mod:darkutils (incompatible), mod:worldedit (incompatible), mod:fastfurnace (incompatible), mod:appleskin, mod:aiimprovements, mod:undergarden, mod:byg, mod:aquaculture (incompatible), mod:friendlyfire (incompatible), mod:deextinction, mod:terraqueous, mod:overloadedarmorbar (incompatible), mod:bettermineshafts (incompatible), mod:geckolib3 (incompatible), mod:cyclic (incompatible), mod:farlanders (incompatible), mod:betteradvancements
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by AzureDoom** [comment] 2020-11-30 10:36
Dupe of #22 UPDATE

**Closed by AzureDoom** 2020-11-30 10:36 UTC
