### ISSUE TITLE
World Failed To Load After 3.0 Update

### ISSUE THREAD

**Issue by IRonicBruh** [AzureDoom/AzureDoom-Doom-Mod#9] opened 2020-09-17 04:26 UTC
After updating from version 1.3.0 to 3.0.0, Attempting to load my world will fail as the game is saying the datapack from the mod is broken. No crash to desktop occurs. The game simply ask's to go into safe mode (no datapacks) or back to main menu.

here's the portion of the log after selecting which world to load. 
https://pastebin.com/eRVBtZjZ

**Comment by IRonicBruh** [comment] 2020-09-17 04:28
The world will load if i revert to the previous version (1.3.0) or remove the mod

**Comment by AzureDoom** [comment] 2020-09-17 15:17
I need the full log please.

**Comment by IRonicBruh** [comment] 2020-09-17 22:26
i would use pastebin but i'm not paying for pro. here's a google drive link;
https://drive.google.com/file/d/1Nm4LCIwhG3KTwuEdlZSHl4q-A1SaA-Iz/view?usp=sharing

**Comment by AzureDoom** [comment] 2020-09-17 22:27
You could use https://gist.github.com lol you do have a github account already :P

**Comment by AzureDoom** [comment] 2020-09-17 22:32
I do have to say though, JFC that is a lot errors but I don't see the error you first listed.

**Comment by IRonicBruh** [comment] 2020-09-18 00:03
To be honest i have no idea whats going on, it's only after i update your mod to the latest version that my world doesn't load. it just gives me this message: Error's in currently selected datapacks prevented the world from loading.

**Comment by IRonicBruh** [comment] 2020-09-18 00:03
and the log remains the same as the one above

**Comment by AzureDoom** [comment] 2020-09-18 00:06
Open the jar and go into `data\curios\tags\items` and delete the bracelet? Only thing I can think of.

**Comment by IRonicBruh** [comment] 2020-09-18 00:59
No dice. It was worth a shot.

**Comment by AzureDoom** [comment] 2020-09-18 01:01
I am honestly stamped sorry, I can't reproduce this on my side. v3.0.0+ and beyond was a MASSIVE code update (roughly 30ish commits alone). With data fixers being trash for mods, sadly I think old saves just may not work due to the changes.

**Comment by IRonicBruh** [comment] 2020-09-18 01:16
I can confirm, Worlds made with version 1.3.0 will not load if the mod updates to 3.0+. I made a few worlds in version 1.3.0 and then updated to 3.1.2., And would get the broken datapack message.

**Comment by AzureDoom** [comment] 2020-09-18 01:23
I just tested with a 1.3.0 world then updated to 3.1.2 and it entered just fine.

**Comment by IRonicBruh** [comment] 2020-09-18 02:10
hmm

**Comment by AzureDoom** [comment] 2020-11-15 04:24
Closing as this shouldn't happen anymore.

**Closed by AzureDoom** 2020-11-15 04:24 UTC
Labels: bug, help wanted
